# Generated by Django 3.1.3 on 2021-06-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoupload', '0002_auto_20210622_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nameAscendency',
            new_name='activePassive',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='gemType',
        ),
    ]
