# Generated by Django 3.1.3 on 2021-06-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoupload', '0003_auto_20210623_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gemName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
